### PR TITLE
update packages to newer versions

### PR DESCRIPTION
**Pull request by Cmdv**
Hi I was just working my way through this [blog post](https://thomashoneyman.com/articles/replace-react-components-with-purescript/) and it was failing as craco & react-scripts have both updated and things just wouldn't compile.

I've tested this locally and it all seems to be aok 👍

### CODE REVIEW

**Comment by andys8** [comment]
Cool. Thanks. Could you tell me what "things just wouldn't compile" means in detail? Could you provide the error message?

There is also a companion repository using this loader, which I would also expect needs to be updated.

https://github.com/andys8/create-react-app-purescript

**Comment by andys8** [comment]
In addition the blog post contains versions and should probably also be updated 

https://github.com/thomashoneyman/writing/blob/main/articles/replace-react-components-with-purescript.md

**Comment by Cmdv** [comment]
@andys8 well it's because of these line:

```
npm install --save @craco/craco
npm install --save-dev craco-purescript-loader
```
https://github.com/thomashoneyman/writing/blob/main/articles/replace-react-components-with-purescript.md?plain=1#L178-L180

so the first line installs the latest version `6.4.0` of `craco` locally to the project and this library is a little behind at `5.6.4` which gives you:

```
hile resolving: my-app@0.1.0
npm ERR! Found: @craco/craco@6.4.0
npm ERR! node_modules/@craco/craco
npm ERR!   @craco/craco@"^6.4.0" from the root project

could not resolve dependency:
npm ERR! peer @craco/craco@"^5.6.4" from craco-purescript-loader@1.0.1
```

one can get around it by using the npm flag `--force` but that always feels a little off to me 😱 

oooh hadn't seen the repo you created too, that should come really handy. I'm attempting to ~convince and~ convert an existing React app into a React-Purescript one in an incremental manner 😄

**Comment by andys8** [comment]
Will update dependencies now :) Thank you

**Comment by Cmdv** [comment]
Thanks @andys8 much appreciated 😄

**Pull request merged**
